spring:
  jpa:
    #전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    #database-platform: org.hibernate.dialect.MySQLDialect
    #테이블 생성 후에 data.sql 실행
    #defer-datasource-initialization: true

  #sql:
    #init:
      #mode: always

  #datasource:
  #  url: jdbc:h2:mem:testdb
  #  username: sa

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: springboot

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 412531422125-ovc9fg8gda995ul69hmfg3ds92ngpku9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  issuer: test@email.com
  secret_key: test_key



